name: Build
on:
  push:
    branches:
    - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: mihails-strasuns/setup-dlang@v0

    - name: Build
      run: dub build